### ISSUE TITLE
ValueError: No value exists in Redis for process ID of: xxx

### ISSUE THREAD

**Issue by domett93** [jesse-ai/jesse#336]
**Describe the bug**
I use Jesse with default Docker Compose from GitHub.
When I run "Optimization" I get always a value error at some step of the process.
It happens with every strategy, timeframe or coin

Same error happens also with "Import Candles" sometimes

Traceback Message:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.9/site-packages/timeloop/job.py", line 19, in run
    self.execute(*self.args, **self.kwargs)
  File "/jesse-docker/jesse/modes/optimize_mode/Optimize.py", line 71, in check_for_termination
    if process_status() != 'started':
  File "/jesse-docker/jesse/services/redis.py", line 64, in process_status
    raise ValueError(f'No value exists in Redis for process ID of: {pid}')
ValueError: No value exists in Redis for process ID of: 4110
```

**To Reproduce**
Just run "Optimization" or  "Import Candles" from GUI Webinterface

**Screenshot**
![Unbenannt2](https://user-images.githubusercontent.com/40364992/159783197-c6696d24-c552-4806-845e-55388f82d9a1.JPG)

**Enviroment (please complete the following information):**
 - Host OS: Ubuntu 20.04.3 LTS
 - Docker Version: 20.10.12
 - Jesse Version: 0.33.3

![Unbenannt](https://user-images.githubusercontent.com/40364992/159783082-75720bf9-4263-426b-8f78-f87b6aa94aef.JPG)

**Comment by saleh-mir** [comment]
Thank you for reporting it. Do you get this error right after starting the containers and starting the optimize mode or after it's been running for a while?

**Comment by domett93** [comment]
I got this error always right after starting the containers
I use the same compose file as you have in the docs (https://github.com/jesse-ai/project-template/blob/main/docker/docker-compose.yml)

At the moment it works for me, but it seems that there was a problem with the redis container
The redis container threw a lot of permission errors like this:

`Failed opening the RDB file crontab (in server root dir /etc) for saving: Permission denied`

Problem was gone after some restarts

**Comment by saleh-mir** [comment]
A while ago that file you linked had a volume defined for Redis which I suspect was the root of the issue. Are you sure yours is exactly that? (I mean the most recent version). Could you please copy and paste yours here just in case?

**Comment by domett93** [comment]
Thats the compose file I use

```
version: '3.5'

services:
  ### Jesse's Workspace ################################################
  jesse:
    image: salehmir/jesse:latest
    depends_on:
      - postgres
      - redis
    tty: true
    env_file:
      - ../.env
    ports:
      - "9000:9000"
      # Jupyter Port
      - "8888:8888"
    volumes:
      - ../:/home
    container_name: jesse
    command: bash -c "jesse install-live --no-strict && jesse run"

  ### PostgreSQL ################################################
  postgres:
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_USER=jesse_user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=jesse_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    container_name: postgres

  ### Redis ################################################
  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"
    container_name: redis

volumes:
  postgres-data:

```

**Comment by saleh-mir** [comment]
It looks just fine. It's a redis issue. I'll keep looking maybe we should change its config.

**Comment by btagliani** [comment]
Definitely something Redis related, probably the address is in use and it cant start. It happened to me (native install, not docker) and it was because my Redis couldn't start. The address was in use by _something_ and a restart fixed it.
```
Name       Status  User  File
memcached  none          
postgresql started bruno ~/Library/LaunchAgents/homebrew.mxcl.postgresql.plist
redis      started bruno ~/Library/LaunchAgents/homebrew.mxcl.redis.plist
```

**Comment by saleh-mir** [comment]
@btagliani did you get `ValueError: No value exists in Redis for process ID of: 4110` too? Because that seems to only happen AFTER the dashboard is already up (so Redis should have been up for a while before throwing this error)

**Comment by btagliani** [comment]
Different PID but yeah same error message.

**Comment by saleh-mir** [comment]
In your `docker-compose.yml` file, after this line:
```
container_name: redis
```
Add this:
```
command: redis-server --save "" --appendonly no
```

Please let me know how it goes. I've been testing it for a while and seems to have done it for me.

**Comment by saleh-mir** [comment]
My last comment seems to have fixed this issue.

**Comment by shhhmel** [comment]
I have the same errors in both "Optimization" and "Backtest" modes.
I'm using Contabo VPS.
<img width="511" alt="Screenshot 2022-06-28 at 17 21 51" src="https://user-images.githubusercontent.com/17930913/176203388-eae5bc96-af82-449b-b65d-88774f71ce6a.png">
<img width="1678" alt="Screenshot 2022-06-28 at 17 20 08" src="https://user-images.githubusercontent.com/17930913/176203399-7b7c4704-57f6-44bf-9ba7-38088bcac53f.png">

Here is the `docker-compose.yml`

```yml
version: '3.5'

services:
  ### Jesse's Workspace ################################################
  jesse:
    image: salehmir/jesse:latest
    depends_on:
      - postgres
      - redis
    tty: true
    env_file:
      - ../.env
    ports:
      - "9000:9000"
      # Jupyter Port
      - "8888:8888"
    volumes:
      - ../:/home
    container_name: jesse
    command: bash -c "jesse install-live --no-strict && jesse run"

  ### PostgreSQL ################################################
  postgres:
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_USER=jesse_user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=jesse_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    container_name: postgres

  ### Redis ################################################
  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"
    container_name: redis
    command: redis-server --save "" --appendonly no
    
volumes:
  postgres-data:
```
